#!/bin/bash

# Sourcing the colors
. $HOME/.cache/wal/colors.sh

ICON_COLOR=${ICON_COLOR:-"$color1"}
LABEL=${LABEL:-"LANG"}

# Left click
if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  	if fcitx5-remote -n | grep -q no; then
  		#switch to japanese
		fcitx5-remote -o
	elif fcitx5-remote -n | grep -q mozc; then
		#switch to Norwegian
		fcitx5-remote -c
	fi
fi

if fcitx5-remote -n | grep -q no; then
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>NO"
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>NO"
elif fcitx5-remote -n | grep -q mozc; then
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>JP"
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>JP"
else
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>NO?"
	echo "<span color=\"$ICON_COLOR\">$LABEL</span>NO?"
fi
echo $color15
