#!/bin/python

import os
import json
import subprocess

STATUS_SCRIPT_PATH = os.path.expanduser("~/RustroverProjects/status/run")

# Load the colors from wal
with open(os.path.expanduser("~/.cache/wal/colors.json"), "r") as f:
    color_data = json.load(f)

highlight_color = color_data["colors"]["color1"]
#highlight_color = color_data["colors"]["color15"]
error_color = "#FF0000"


# Now for communicating with rust
proc = subprocess.Popen([STATUS_SCRIPT_PATH, "service"], stdout=subprocess.PIPE)
output, _ = proc.communicate()
data = json.loads(output)


str_builder = ""
for service in data:
    if service["successes"] >= 1.0:
        str_builder += f'<span color="{highlight_color}">I</span>'
    else:
        str_builder += f'<span color="{error_color}">I</span>'


print(str_builder)
print(str_builder)
print(color_data["colors"]["color15"])
